/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2095.0) */

#include "service_if.h"
#include <stdint.h>
#include "app_trace.h" 
#include "ble_gpio_test_service.h" 

static ble_gpio_test_service_t    m_gpio_test_service; 



/**@brief Function for handling the GPIO Test Service events.
 *
 * @details This function will be called for all GPIO Test Service events which are passed to
 *          the application.
 *
 * @param[in]   p_gpio_test_service   GPIO Test Service structure.
 * @param[in]   p_evt   Event received from the GPIO Test Service.
 */
static void on_gpio_test_service_evt(ble_gpio_test_service_t * p_gpio_test_service, ble_gpio_test_service_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_GPIO_TEST_SERVICE_LED_EVT_WRITE:
            app_trace_log("[Bluetooth_IF]: GPIO_TEST_SERVICE_LED evt WRITE. \r\n");
            break; 
        case BLE_GPIO_TEST_SERVICE_BUTTON_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: GPIO_TEST_SERVICE_BUTTON evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_GPIO_TEST_SERVICE_BUTTON_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: GPIO_TEST_SERVICE_BUTTON evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_GPIO_TEST_SERVICE_BUTTON_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: GPIO_TEST_SERVICE_BUTTON evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_gpio_test_service_init_t    gpio_test_service_init; 
    

    // Initialize GPIO Test Service.
    memset(&gpio_test_service_init, 0, sizeof(gpio_test_service_init));

    gpio_test_service_init.evt_handler = on_gpio_test_service_evt; 
    memset(&gpio_test_service_init.ble_gpio_test_service_led_initial_value.toggle_led,
           0x00,
           sizeof(gpio_test_service_init.ble_gpio_test_service_led_initial_value.toggle_led));
    memset(&gpio_test_service_init.ble_gpio_test_service_button_initial_value.button_state,
           0x00,
           sizeof(gpio_test_service_init.ble_gpio_test_service_button_initial_value.button_state));

    err_code = ble_gpio_test_service_init(&m_gpio_test_service, &gpio_test_service_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_gpio_test_service_on_ble_evt(&m_gpio_test_service, p_ble_evt); 
}
